// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file zenao/v1/zenao.proto (package zenao.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zenao/v1/zenao.proto.
 */
export const file_zenao_v1_zenao: GenFile = /*@__PURE__*/
  fileDesc("ChR6ZW5hby92MS96ZW5hby5wcm90bxIIemVuYW8udjEiSAoPRWRpdFVzZXJSZXF1ZXN0EhQKDGRpc3BsYXlfbmFtZRgBIAEoCRILCgNiaW8YAiABKAkSEgoKYXZhdGFyX3VyaRgDIAEoCSIeChBFZGl0VXNlclJlc3BvbnNlEgoKAmlkGAEgASgJIhcKFUdldFVzZXJBZGRyZXNzUmVxdWVzdCIpChZHZXRVc2VyQWRkcmVzc1Jlc3BvbnNlEg8KB2FkZHJlc3MYASABKAkiqwEKEkNyZWF0ZUV2ZW50UmVxdWVzdBINCgV0aXRsZRgBIAEoCRITCgtkZXNjcmlwdGlvbhgCIAEoCRIRCglpbWFnZV91cmkYAyABKAkSEgoKc3RhcnRfZGF0ZRgEIAEoBBIQCghlbmRfZGF0ZRgFIAEoBBIUCgx0aWNrZXRfcHJpY2UYBiABKAESEAoIY2FwYWNpdHkYByABKA0SEAoIbG9jYXRpb24YCCABKAkiIQoTQ3JlYXRlRXZlbnRSZXNwb25zZRIKCgJpZBgBIAEoCSK7AQoQRWRpdEV2ZW50UmVxdWVzdBIQCghldmVudF9pZBgBIAEoCRINCgV0aXRsZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRIRCglpbWFnZV91cmkYBCABKAkSEgoKc3RhcnRfZGF0ZRgFIAEoBBIQCghlbmRfZGF0ZRgGIAEoBBIUCgx0aWNrZXRfcHJpY2UYByABKAESEAoIY2FwYWNpdHkYCCABKA0SEAoIbG9jYXRpb24YCSABKAkiHwoRRWRpdEV2ZW50UmVzcG9uc2USCgoCaWQYASABKAkiJgoSUGFydGljaXBhdGVSZXF1ZXN0EhAKCGV2ZW50X2lkGAEgASgJIiwKE1BhcnRpY2lwYXRlUmVzcG9uc2USFQoNdGlja2V0X3NlY3JldBgBIAEoCTKEAwoMWmVuYW9TZXJ2aWNlEkEKCEVkaXRVc2VyEhkuemVuYW8udjEuRWRpdFVzZXJSZXF1ZXN0GhouemVuYW8udjEuRWRpdFVzZXJSZXNwb25zZRJTCg5HZXRVc2VyQWRkcmVzcxIfLnplbmFvLnYxLkdldFVzZXJBZGRyZXNzUmVxdWVzdBogLnplbmFvLnYxLkdldFVzZXJBZGRyZXNzUmVzcG9uc2USSgoLQ3JlYXRlRXZlbnQSHC56ZW5hby52MS5DcmVhdGVFdmVudFJlcXVlc3QaHS56ZW5hby52MS5DcmVhdGVFdmVudFJlc3BvbnNlEkQKCUVkaXRFdmVudBIaLnplbmFvLnYxLkVkaXRFdmVudFJlcXVlc3QaGy56ZW5hby52MS5FZGl0RXZlbnRSZXNwb25zZRJKCgtQYXJ0aWNpcGF0ZRIcLnplbmFvLnYxLlBhcnRpY2lwYXRlUmVxdWVzdBodLnplbmFvLnYxLlBhcnRpY2lwYXRlUmVzcG9uc2VCOVo3Z2l0aHViLmNvbS9zYW1vdXJhaXdvcmxkL3plbmFvL2JhY2tlbmQvemVuYW8vdjE7emVuYW92MWIGcHJvdG8z");

/**
 * @generated from message zenao.v1.EditUserRequest
 */
export type EditUserRequest = Message<"zenao.v1.EditUserRequest"> & {
  /**
   * @generated from field: string display_name = 1;
   */
  displayName: string;

  /**
   * @generated from field: string bio = 2;
   */
  bio: string;

  /**
   * @generated from field: string avatar_uri = 3;
   */
  avatarUri: string;
};

/**
 * Describes the message zenao.v1.EditUserRequest.
 * Use `create(EditUserRequestSchema)` to create a new message.
 */
export const EditUserRequestSchema: GenMessage<EditUserRequest> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 0);

/**
 * @generated from message zenao.v1.EditUserResponse
 */
export type EditUserResponse = Message<"zenao.v1.EditUserResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message zenao.v1.EditUserResponse.
 * Use `create(EditUserResponseSchema)` to create a new message.
 */
export const EditUserResponseSchema: GenMessage<EditUserResponse> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 1);

/**
 * @generated from message zenao.v1.GetUserAddressRequest
 */
export type GetUserAddressRequest = Message<"zenao.v1.GetUserAddressRequest"> & {
};

/**
 * Describes the message zenao.v1.GetUserAddressRequest.
 * Use `create(GetUserAddressRequestSchema)` to create a new message.
 */
export const GetUserAddressRequestSchema: GenMessage<GetUserAddressRequest> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 2);

/**
 * @generated from message zenao.v1.GetUserAddressResponse
 */
export type GetUserAddressResponse = Message<"zenao.v1.GetUserAddressResponse"> & {
  /**
   * @generated from field: string address = 1;
   */
  address: string;
};

/**
 * Describes the message zenao.v1.GetUserAddressResponse.
 * Use `create(GetUserAddressResponseSchema)` to create a new message.
 */
export const GetUserAddressResponseSchema: GenMessage<GetUserAddressResponse> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 3);

/**
 * @generated from message zenao.v1.CreateEventRequest
 */
export type CreateEventRequest = Message<"zenao.v1.CreateEventRequest"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * @generated from field: string image_uri = 3;
   */
  imageUri: string;

  /**
   * unix seconds
   *
   * @generated from field: uint64 start_date = 4;
   */
  startDate: bigint;

  /**
   * unix seconds
   *
   * @generated from field: uint64 end_date = 5;
   */
  endDate: bigint;

  /**
   * XXX: use fixed point?
   *
   * @generated from field: double ticket_price = 6;
   */
  ticketPrice: number;

  /**
   * @generated from field: uint32 capacity = 7;
   */
  capacity: number;

  /**
   * @generated from field: string location = 8;
   */
  location: string;
};

/**
 * Describes the message zenao.v1.CreateEventRequest.
 * Use `create(CreateEventRequestSchema)` to create a new message.
 */
export const CreateEventRequestSchema: GenMessage<CreateEventRequest> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 4);

/**
 * @generated from message zenao.v1.CreateEventResponse
 */
export type CreateEventResponse = Message<"zenao.v1.CreateEventResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message zenao.v1.CreateEventResponse.
 * Use `create(CreateEventResponseSchema)` to create a new message.
 */
export const CreateEventResponseSchema: GenMessage<CreateEventResponse> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 5);

/**
 * @generated from message zenao.v1.EditEventRequest
 */
export type EditEventRequest = Message<"zenao.v1.EditEventRequest"> & {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: string image_uri = 4;
   */
  imageUri: string;

  /**
   * unix seconds
   *
   * @generated from field: uint64 start_date = 5;
   */
  startDate: bigint;

  /**
   * unix seconds
   *
   * @generated from field: uint64 end_date = 6;
   */
  endDate: bigint;

  /**
   * XXX: use fixed point?
   *
   * @generated from field: double ticket_price = 7;
   */
  ticketPrice: number;

  /**
   * @generated from field: uint32 capacity = 8;
   */
  capacity: number;

  /**
   * @generated from field: string location = 9;
   */
  location: string;
};

/**
 * Describes the message zenao.v1.EditEventRequest.
 * Use `create(EditEventRequestSchema)` to create a new message.
 */
export const EditEventRequestSchema: GenMessage<EditEventRequest> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 6);

/**
 * @generated from message zenao.v1.EditEventResponse
 */
export type EditEventResponse = Message<"zenao.v1.EditEventResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message zenao.v1.EditEventResponse.
 * Use `create(EditEventResponseSchema)` to create a new message.
 */
export const EditEventResponseSchema: GenMessage<EditEventResponse> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 7);

/**
 * @generated from message zenao.v1.ParticipateRequest
 */
export type ParticipateRequest = Message<"zenao.v1.ParticipateRequest"> & {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId: string;
};

/**
 * Describes the message zenao.v1.ParticipateRequest.
 * Use `create(ParticipateRequestSchema)` to create a new message.
 */
export const ParticipateRequestSchema: GenMessage<ParticipateRequest> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 8);

/**
 * @generated from message zenao.v1.ParticipateResponse
 */
export type ParticipateResponse = Message<"zenao.v1.ParticipateResponse"> & {
  /**
   * @generated from field: string ticket_secret = 1;
   */
  ticketSecret: string;
};

/**
 * Describes the message zenao.v1.ParticipateResponse.
 * Use `create(ParticipateResponseSchema)` to create a new message.
 */
export const ParticipateResponseSchema: GenMessage<ParticipateResponse> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 9);

/**
 * @generated from service zenao.v1.ZenaoService
 */
export const ZenaoService: GenService<{
  /**
   * USER
   *
   * @generated from rpc zenao.v1.ZenaoService.EditUser
   */
  editUser: {
    methodKind: "unary";
    input: typeof EditUserRequestSchema;
    output: typeof EditUserResponseSchema;
  },
  /**
   * @generated from rpc zenao.v1.ZenaoService.GetUserAddress
   */
  getUserAddress: {
    methodKind: "unary";
    input: typeof GetUserAddressRequestSchema;
    output: typeof GetUserAddressResponseSchema;
  },
  /**
   * EVENT
   *
   * @generated from rpc zenao.v1.ZenaoService.CreateEvent
   */
  createEvent: {
    methodKind: "unary";
    input: typeof CreateEventRequestSchema;
    output: typeof CreateEventResponseSchema;
  },
  /**
   * @generated from rpc zenao.v1.ZenaoService.EditEvent
   */
  editEvent: {
    methodKind: "unary";
    input: typeof EditEventRequestSchema;
    output: typeof EditEventResponseSchema;
  },
  /**
   * @generated from rpc zenao.v1.ZenaoService.Participate
   */
  participate: {
    methodKind: "unary";
    input: typeof ParticipateRequestSchema;
    output: typeof ParticipateResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_zenao_v1_zenao, 0);

