// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file zenao/v1/zenao.proto (package zenao.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zenao/v1/zenao.proto.
 */
export const file_zenao_v1_zenao: GenFile = /*@__PURE__*/
  fileDesc("ChR6ZW5hby92MS96ZW5hby5wcm90bxIIemVuYW8udjEiFAoSQ3JlYXRlRXZlbnRSZXF1ZXN0IhUKE0NyZWF0ZUV2ZW50UmVzcG9uc2UyWgoMWmVuYW9TZXJ2aWNlEkoKC0NyZWF0ZUV2ZW50EhwuemVuYW8udjEuQ3JlYXRlRXZlbnRSZXF1ZXN0Gh0uemVuYW8udjEuQ3JlYXRlRXZlbnRSZXNwb25zZUI5WjdnaXRodWIuY29tL3NhbW91cmFpd29ybGQvemVuYW8vYmFja2VuZC96ZW5hby92MTt6ZW5hb3YxYgZwcm90bzM");

/**
 * @generated from message zenao.v1.CreateEventRequest
 */
export type CreateEventRequest = Message<"zenao.v1.CreateEventRequest"> & {
};

/**
 * Describes the message zenao.v1.CreateEventRequest.
 * Use `create(CreateEventRequestSchema)` to create a new message.
 */
export const CreateEventRequestSchema: GenMessage<CreateEventRequest> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 0);

/**
 * @generated from message zenao.v1.CreateEventResponse
 */
export type CreateEventResponse = Message<"zenao.v1.CreateEventResponse"> & {
};

/**
 * Describes the message zenao.v1.CreateEventResponse.
 * Use `create(CreateEventResponseSchema)` to create a new message.
 */
export const CreateEventResponseSchema: GenMessage<CreateEventResponse> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 1);

/**
 * @generated from service zenao.v1.ZenaoService
 */
export const ZenaoService: GenService<{
  /**
   * @generated from rpc zenao.v1.ZenaoService.CreateEvent
   */
  createEvent: {
    methodKind: "unary";
    input: typeof CreateEventRequestSchema;
    output: typeof CreateEventResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_zenao_v1_zenao, 0);

