// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file zenao/v1/zenao.proto (package zenao.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zenao/v1/zenao.proto.
 */
export const file_zenao_v1_zenao: GenFile = /*@__PURE__*/
  fileDesc("ChR6ZW5hby92MS96ZW5hby5wcm90bxIIemVuYW8udjEimQEKEkNyZWF0ZUV2ZW50UmVxdWVzdBINCgV0aXRsZRgBIAEoCRITCgtkZXNjcmlwdGlvbhgCIAEoCRIRCglpbWFnZV91cmkYAyABKAkSEgoKc3RhcnRfZGF0ZRgEIAEoBBIQCghlbmRfZGF0ZRgFIAEoBBIUCgx0aWNrZXRfcHJpY2UYBiABKAESEAoIY2FwYWNpdHkYByABKA0iIQoTQ3JlYXRlRXZlbnRSZXNwb25zZRIKCgJpZBgBIAEoCSIlChFDcmVhdGVVc2VyUmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCSIgChJDcmVhdGVVc2VyUmVzcG9uc2USCgoCaWQYASABKAkiTAoPRWRpdFVzZXJSZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEhMKC2Rlc2NyaXB0aW9uGAIgASgJEhIKCmF2YXRhcl91cmkYAyABKAkiHgoQRWRpdFVzZXJSZXNwb25zZRIKCgJpZBgBIAEoCTLmAQoMWmVuYW9TZXJ2aWNlEkoKC0NyZWF0ZUV2ZW50EhwuemVuYW8udjEuQ3JlYXRlRXZlbnRSZXF1ZXN0Gh0uemVuYW8udjEuQ3JlYXRlRXZlbnRSZXNwb25zZRJHCgpDcmVhdGVVc2VyEhsuemVuYW8udjEuQ3JlYXRlVXNlclJlcXVlc3QaHC56ZW5hby52MS5DcmVhdGVVc2VyUmVzcG9uc2USQQoIRWRpdFVzZXISGS56ZW5hby52MS5FZGl0VXNlclJlcXVlc3QaGi56ZW5hby52MS5FZGl0VXNlclJlc3BvbnNlQjlaN2dpdGh1Yi5jb20vc2Ftb3VyYWl3b3JsZC96ZW5hby9iYWNrZW5kL3plbmFvL3YxO3plbmFvdjFiBnByb3RvMw");

/**
 * @generated from message zenao.v1.CreateEventRequest
 */
export type CreateEventRequest = Message<"zenao.v1.CreateEventRequest"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * @generated from field: string image_uri = 3;
   */
  imageUri: string;

  /**
   * unix seconds
   *
   * @generated from field: uint64 start_date = 4;
   */
  startDate: bigint;

  /**
   * unix seconds
   *
   * @generated from field: uint64 end_date = 5;
   */
  endDate: bigint;

  /**
   * XXX: use fixed point?
   *
   * @generated from field: double ticket_price = 6;
   */
  ticketPrice: number;

  /**
   * @generated from field: uint32 capacity = 7;
   */
  capacity: number;
};

/**
 * Describes the message zenao.v1.CreateEventRequest.
 * Use `create(CreateEventRequestSchema)` to create a new message.
 */
export const CreateEventRequestSchema: GenMessage<CreateEventRequest> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 0);

/**
 * @generated from message zenao.v1.CreateEventResponse
 */
export type CreateEventResponse = Message<"zenao.v1.CreateEventResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message zenao.v1.CreateEventResponse.
 * Use `create(CreateEventResponseSchema)` to create a new message.
 */
export const CreateEventResponseSchema: GenMessage<CreateEventResponse> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 1);

/**
 * @generated from message zenao.v1.CreateUserRequest
 */
export type CreateUserRequest = Message<"zenao.v1.CreateUserRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;
};

/**
 * Describes the message zenao.v1.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export const CreateUserRequestSchema: GenMessage<CreateUserRequest> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 2);

/**
 * @generated from message zenao.v1.CreateUserResponse
 */
export type CreateUserResponse = Message<"zenao.v1.CreateUserResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message zenao.v1.CreateUserResponse.
 * Use `create(CreateUserResponseSchema)` to create a new message.
 */
export const CreateUserResponseSchema: GenMessage<CreateUserResponse> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 3);

/**
 * @generated from message zenao.v1.EditUserRequest
 */
export type EditUserRequest = Message<"zenao.v1.EditUserRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * @generated from field: string avatar_uri = 3;
   */
  avatarUri: string;
};

/**
 * Describes the message zenao.v1.EditUserRequest.
 * Use `create(EditUserRequestSchema)` to create a new message.
 */
export const EditUserRequestSchema: GenMessage<EditUserRequest> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 4);

/**
 * @generated from message zenao.v1.EditUserResponse
 */
export type EditUserResponse = Message<"zenao.v1.EditUserResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message zenao.v1.EditUserResponse.
 * Use `create(EditUserResponseSchema)` to create a new message.
 */
export const EditUserResponseSchema: GenMessage<EditUserResponse> = /*@__PURE__*/
  messageDesc(file_zenao_v1_zenao, 5);

/**
 * @generated from service zenao.v1.ZenaoService
 */
export const ZenaoService: GenService<{
  /**
   * @generated from rpc zenao.v1.ZenaoService.CreateEvent
   */
  createEvent: {
    methodKind: "unary";
    input: typeof CreateEventRequestSchema;
    output: typeof CreateEventResponseSchema;
  },
  /**
   * @generated from rpc zenao.v1.ZenaoService.CreateUser
   */
  createUser: {
    methodKind: "unary";
    input: typeof CreateUserRequestSchema;
    output: typeof CreateUserResponseSchema;
  },
  /**
   * @generated from rpc zenao.v1.ZenaoService.EditUser
   */
  editUser: {
    methodKind: "unary";
    input: typeof EditUserRequestSchema;
    output: typeof EditUserResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_zenao_v1_zenao, 0);

