# fly.toml app configuration file generated for zenao-staging on 2025-01-26T18:17:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zenao-staging'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 4242
  force_https = true
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 1024
