# fly.toml app configuration file generated for zenao-gno on 2025-01-24T02:36:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zenao-gno'
primary_region = 'cdg'

[build]
dockerfile = 'gno.Dockerfile'
[build.args]
ZENAO_ADMIN_ADDR = 'g1djrkw9tf4px658j85cc6fhsvm50uf9s0g6kfsm'

[http_service]
internal_port = 8888
force_https = true
processes = ['app']

[[services]]
protocol = 'tcp'
internal_port = 26657

[[services.ports]]
port = 26657
handlers = ['tls', 'http']

[[vm]]
cpu_kind = 'performance'
cpus = 2
memory_mb = 4096
