# fly.toml app configuration file generated for zenao on 2025-01-24T01:12:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zenao'
primary_region = 'cdg'

[build]
dockerfile = 'Dockerfile'

[http_service]
internal_port = 4242
force_https = true
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 2
memory_mb = 1024
