// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: polls/v1/polls.proto

package pollsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PollResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Option        string                 `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	HasUserVoted  bool                   `protobuf:"varint,3,opt,name=has_user_voted,json=hasUserVoted,proto3" json:"has_user_voted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResult) Reset() {
	*x = PollResult{}
	mi := &file_polls_v1_polls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResult) ProtoMessage() {}

func (x *PollResult) ProtoReflect() protoreflect.Message {
	mi := &file_polls_v1_polls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResult.ProtoReflect.Descriptor instead.
func (*PollResult) Descriptor() ([]byte, []int) {
	return file_polls_v1_polls_proto_rawDescGZIP(), []int{0}
}

func (x *PollResult) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

func (x *PollResult) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PollResult) GetHasUserVoted() bool {
	if x != nil {
		return x.HasUserVoted
	}
	return false
}

type Poll struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Question        string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Results         []*PollResult          `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	MultipleChoices bool                   `protobuf:"varint,3,opt,name=multiple_choices,json=multipleChoices,proto3" json:"multiple_choices,omitempty"`
	Duration        int64                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy       string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Poll) Reset() {
	*x = Poll{}
	mi := &file_polls_v1_polls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Poll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poll) ProtoMessage() {}

func (x *Poll) ProtoReflect() protoreflect.Message {
	mi := &file_polls_v1_polls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poll.ProtoReflect.Descriptor instead.
func (*Poll) Descriptor() ([]byte, []int) {
	return file_polls_v1_polls_proto_rawDescGZIP(), []int{1}
}

func (x *Poll) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Poll) GetResults() []*PollResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *Poll) GetMultipleChoices() bool {
	if x != nil {
		return x.MultipleChoices
	}
	return false
}

func (x *Poll) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Poll) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Poll) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

var File_polls_v1_polls_proto protoreflect.FileDescriptor

var file_polls_v1_polls_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x70, 0x6f, 0x6c, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x6c, 0x6c, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x6f, 0x6c, 0x6c, 0x73, 0x2e, 0x76, 0x31,
	0x22, 0x60, 0x0a, 0x0a, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0e,
	0x68, 0x61, 0x73, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x76, 0x6f, 0x74, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x68, 0x61, 0x73, 0x55, 0x73, 0x65, 0x72, 0x56, 0x6f, 0x74,
	0x65, 0x64, 0x22, 0xd7, 0x01, 0x0a, 0x04, 0x50, 0x6f, 0x6c, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6f, 0x6c, 0x6c, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x65, 0x5f, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x43, 0x68, 0x6f, 0x69, 0x63,
	0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x42, 0x39, 0x5a, 0x37,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x61, 0x6d, 0x6f, 0x75,
	0x72, 0x61, 0x69, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x7a, 0x65, 0x6e, 0x61, 0x6f, 0x2f, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6f, 0x6c, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x3b,
	0x70, 0x6f, 0x6c, 0x6c, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_polls_v1_polls_proto_rawDescOnce sync.Once
	file_polls_v1_polls_proto_rawDescData []byte
)

func file_polls_v1_polls_proto_rawDescGZIP() []byte {
	file_polls_v1_polls_proto_rawDescOnce.Do(func() {
		file_polls_v1_polls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polls_v1_polls_proto_rawDesc), len(file_polls_v1_polls_proto_rawDesc)))
	})
	return file_polls_v1_polls_proto_rawDescData
}

var file_polls_v1_polls_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_polls_v1_polls_proto_goTypes = []any{
	(*PollResult)(nil), // 0: polls.v1.PollResult
	(*Poll)(nil),       // 1: polls.v1.Poll
}
var file_polls_v1_polls_proto_depIdxs = []int32{
	0, // 0: polls.v1.Poll.results:type_name -> polls.v1.PollResult
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_polls_v1_polls_proto_init() }
func file_polls_v1_polls_proto_init() {
	if File_polls_v1_polls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polls_v1_polls_proto_rawDesc), len(file_polls_v1_polls_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_polls_v1_polls_proto_goTypes,
		DependencyIndexes: file_polls_v1_polls_proto_depIdxs,
		MessageInfos:      file_polls_v1_polls_proto_msgTypes,
	}.Build()
	File_polls_v1_polls_proto = out.File
	file_polls_v1_polls_proto_goTypes = nil
	file_polls_v1_polls_proto_depIdxs = nil
}
