// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: polls/v1/polls.proto

package pollsv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PollKind int32

const (
	PollKind_POLL_KIND_UNSPECIFIED     PollKind = 0
	PollKind_POLL_KIND_SINGLE_CHOICE   PollKind = 1
	PollKind_POLL_KIND_MULTIPLE_CHOICE PollKind = 2
)

// Enum value maps for PollKind.
var (
	PollKind_name = map[int32]string{
		0: "POLL_KIND_UNSPECIFIED",
		1: "POLL_KIND_SINGLE_CHOICE",
		2: "POLL_KIND_MULTIPLE_CHOICE",
	}
	PollKind_value = map[string]int32{
		"POLL_KIND_UNSPECIFIED":     0,
		"POLL_KIND_SINGLE_CHOICE":   1,
		"POLL_KIND_MULTIPLE_CHOICE": 2,
	}
)

func (x PollKind) Enum() *PollKind {
	p := new(PollKind)
	*p = x
	return p
}

func (x PollKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PollKind) Descriptor() protoreflect.EnumDescriptor {
	return file_polls_v1_polls_proto_enumTypes[0].Descriptor()
}

func (PollKind) Type() protoreflect.EnumType {
	return &file_polls_v1_polls_proto_enumTypes[0]
}

func (x PollKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PollKind.Descriptor instead.
func (PollKind) EnumDescriptor() ([]byte, []int) {
	return file_polls_v1_polls_proto_rawDescGZIP(), []int{0}
}

type PollResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Option        string                 `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	HasUserVoted  bool                   `protobuf:"varint,3,opt,name=has_user_voted,json=hasUserVoted,proto3" json:"has_user_voted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResult) Reset() {
	*x = PollResult{}
	mi := &file_polls_v1_polls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResult) ProtoMessage() {}

func (x *PollResult) ProtoReflect() protoreflect.Message {
	mi := &file_polls_v1_polls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResult.ProtoReflect.Descriptor instead.
func (*PollResult) Descriptor() ([]byte, []int) {
	return file_polls_v1_polls_proto_rawDescGZIP(), []int{0}
}

func (x *PollResult) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

func (x *PollResult) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PollResult) GetHasUserVoted() bool {
	if x != nil {
		return x.HasUserVoted
	}
	return false
}

type Poll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Results       []*PollResult          `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Kind          PollKind               `protobuf:"varint,3,opt,name=kind,proto3,enum=polls.v1.PollKind" json:"kind,omitempty"`
	Duration      int64                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Poll) Reset() {
	*x = Poll{}
	mi := &file_polls_v1_polls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Poll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poll) ProtoMessage() {}

func (x *Poll) ProtoReflect() protoreflect.Message {
	mi := &file_polls_v1_polls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poll.ProtoReflect.Descriptor instead.
func (*Poll) Descriptor() ([]byte, []int) {
	return file_polls_v1_polls_proto_rawDescGZIP(), []int{1}
}

func (x *Poll) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Poll) GetResults() []*PollResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *Poll) GetKind() PollKind {
	if x != nil {
		return x.Kind
	}
	return PollKind_POLL_KIND_UNSPECIFIED
}

func (x *Poll) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Poll) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Poll) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

var File_polls_v1_polls_proto protoreflect.FileDescriptor

const file_polls_v1_polls_proto_rawDesc = "" +
	"\n" +
	"\x14polls/v1/polls.proto\x12\bpolls.v1\"`\n" +
	"\n" +
	"PollResult\x12\x16\n" +
	"\x06option\x18\x01 \x01(\tR\x06option\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12$\n" +
	"\x0ehas_user_voted\x18\x03 \x01(\bR\fhasUserVoted\"\xd4\x01\n" +
	"\x04Poll\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12.\n" +
	"\aresults\x18\x02 \x03(\v2\x14.polls.v1.PollResultR\aresults\x12&\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x12.polls.v1.PollKindR\x04kind\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x03R\bduration\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy*a\n" +
	"\bPollKind\x12\x19\n" +
	"\x15POLL_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17POLL_KIND_SINGLE_CHOICE\x10\x01\x12\x1d\n" +
	"\x19POLL_KIND_MULTIPLE_CHOICE\x10\x02B9Z7github.com/samouraiworld/zenao/backend/polls/v1;pollsv1b\x06proto3"

var (
	file_polls_v1_polls_proto_rawDescOnce sync.Once
	file_polls_v1_polls_proto_rawDescData []byte
)

func file_polls_v1_polls_proto_rawDescGZIP() []byte {
	file_polls_v1_polls_proto_rawDescOnce.Do(func() {
		file_polls_v1_polls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polls_v1_polls_proto_rawDesc), len(file_polls_v1_polls_proto_rawDesc)))
	})
	return file_polls_v1_polls_proto_rawDescData
}

var file_polls_v1_polls_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_polls_v1_polls_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_polls_v1_polls_proto_goTypes = []any{
	(PollKind)(0),      // 0: polls.v1.PollKind
	(*PollResult)(nil), // 1: polls.v1.PollResult
	(*Poll)(nil),       // 2: polls.v1.Poll
}
var file_polls_v1_polls_proto_depIdxs = []int32{
	1, // 0: polls.v1.Poll.results:type_name -> polls.v1.PollResult
	0, // 1: polls.v1.Poll.kind:type_name -> polls.v1.PollKind
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_polls_v1_polls_proto_init() }
func file_polls_v1_polls_proto_init() {
	if File_polls_v1_polls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polls_v1_polls_proto_rawDesc), len(file_polls_v1_polls_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_polls_v1_polls_proto_goTypes,
		DependencyIndexes: file_polls_v1_polls_proto_depIdxs,
		EnumInfos:         file_polls_v1_polls_proto_enumTypes,
		MessageInfos:      file_polls_v1_polls_proto_msgTypes,
	}.Build()
	File_polls_v1_polls_proto = out.File
	file_polls_v1_polls_proto_goTypes = nil
	file_polls_v1_polls_proto_depIdxs = nil
}
