// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        (unknown)
// source: zenao/v1/zenao.proto

package zenaov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_zenao_v1_zenao_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zenao_v1_zenao_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_zenao_v1_zenao_proto_rawDescGZIP(), []int{0}
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_zenao_v1_zenao_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zenao_v1_zenao_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_zenao_v1_zenao_proto_rawDescGZIP(), []int{1}
}

var File_zenao_v1_zenao_proto protoreflect.FileDescriptor

var file_zenao_v1_zenao_proto_rawDesc = []byte{
	0x0a, 0x14, 0x7a, 0x65, 0x6e, 0x61, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x7a, 0x65, 0x6e, 0x61, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x7a, 0x65, 0x6e, 0x61, 0x6f, 0x2e, 0x76, 0x31,
	0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x5a, 0x0a,
	0x0c, 0x5a, 0x65, 0x6e, 0x61, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a,
	0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x2e, 0x7a,
	0x65, 0x6e, 0x61, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x7a, 0x65, 0x6e,
	0x61, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x61, 0x6d, 0x6f, 0x75, 0x72, 0x61, 0x69,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x7a, 0x65, 0x6e, 0x61, 0x6f, 0x2f, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2f, 0x7a, 0x65, 0x6e, 0x61, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x7a, 0x65, 0x6e,
	0x61, 0x6f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zenao_v1_zenao_proto_rawDescOnce sync.Once
	file_zenao_v1_zenao_proto_rawDescData = file_zenao_v1_zenao_proto_rawDesc
)

func file_zenao_v1_zenao_proto_rawDescGZIP() []byte {
	file_zenao_v1_zenao_proto_rawDescOnce.Do(func() {
		file_zenao_v1_zenao_proto_rawDescData = protoimpl.X.CompressGZIP(file_zenao_v1_zenao_proto_rawDescData)
	})
	return file_zenao_v1_zenao_proto_rawDescData
}

var file_zenao_v1_zenao_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_zenao_v1_zenao_proto_goTypes = []any{
	(*CreateEventRequest)(nil),  // 0: zenao.v1.CreateEventRequest
	(*CreateEventResponse)(nil), // 1: zenao.v1.CreateEventResponse
}
var file_zenao_v1_zenao_proto_depIdxs = []int32{
	0, // 0: zenao.v1.ZenaoService.CreateEvent:input_type -> zenao.v1.CreateEventRequest
	1, // 1: zenao.v1.ZenaoService.CreateEvent:output_type -> zenao.v1.CreateEventResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zenao_v1_zenao_proto_init() }
func file_zenao_v1_zenao_proto_init() {
	if File_zenao_v1_zenao_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zenao_v1_zenao_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zenao_v1_zenao_proto_goTypes,
		DependencyIndexes: file_zenao_v1_zenao_proto_depIdxs,
		MessageInfos:      file_zenao_v1_zenao_proto_msgTypes,
	}.Build()
	File_zenao_v1_zenao_proto = out.File
	file_zenao_v1_zenao_proto_rawDesc = nil
	file_zenao_v1_zenao_proto_goTypes = nil
	file_zenao_v1_zenao_proto_depIdxs = nil
}
