// Code generated by protoc-gen-go-gnolit. DO NOT EDIT.

package zenaov1

import (
	"strings"
	"fmt"
	"errors"
)

func (e *EditUserRequest) GnoLiteral(typePrefix string, linePrefix string) string {
	buf := &strings.Builder{}
	buf.WriteString(typePrefix)
	buf.WriteString("EditUserRequest{\n")
	fmt.Fprintf(buf, "%s\tDisplayName: %q,\n", linePrefix, e.DisplayName)
	fmt.Fprintf(buf, "%s\tBio: %q,\n", linePrefix, e.Bio)
	fmt.Fprintf(buf, "%s\tAvatarUri: %q,\n", linePrefix, e.AvatarUri)
	buf.WriteString(linePrefix)
	buf.WriteString("}")
	return buf.String()
}

func (e *EditUserResponse) GnoLiteral(typePrefix string, linePrefix string) string {
	buf := &strings.Builder{}
	buf.WriteString(typePrefix)
	buf.WriteString("EditUserResponse{\n")
	fmt.Fprintf(buf, "%s\tId: %q,\n", linePrefix, e.Id)
	buf.WriteString(linePrefix)
	buf.WriteString("}")
	return buf.String()
}

func (g *GetUserAddressRequest) GnoLiteral(typePrefix string, linePrefix string) string {
	buf := &strings.Builder{}
	buf.WriteString(typePrefix)
	buf.WriteString("GetUserAddressRequest{\n")
	buf.WriteString(linePrefix)
	buf.WriteString("}")
	return buf.String()
}

func (g *GetUserAddressResponse) GnoLiteral(typePrefix string, linePrefix string) string {
	buf := &strings.Builder{}
	buf.WriteString(typePrefix)
	buf.WriteString("GetUserAddressResponse{\n")
	fmt.Fprintf(buf, "%s\tAddress: %q,\n", linePrefix, g.Address)
	buf.WriteString(linePrefix)
	buf.WriteString("}")
	return buf.String()
}

func (c *CreateEventRequest) GnoLiteral(typePrefix string, linePrefix string) string {
	buf := &strings.Builder{}
	buf.WriteString(typePrefix)
	buf.WriteString("CreateEventRequest{\n")
	fmt.Fprintf(buf, "%s\tTitle: %q,\n", linePrefix, c.Title)
	fmt.Fprintf(buf, "%s\tDescription: %q,\n", linePrefix, c.Description)
	fmt.Fprintf(buf, "%s\tImageUri: %q,\n", linePrefix, c.ImageUri)
	fmt.Fprintf(buf, "%s\tStartDate: %d,\n", linePrefix, c.StartDate)
	fmt.Fprintf(buf, "%s\tEndDate: %d,\n", linePrefix, c.EndDate)
	fmt.Fprintf(buf, "%s\tTicketPrice: %g,\n", linePrefix, c.TicketPrice)
	fmt.Fprintf(buf, "%s\tCapacity: %d,\n", linePrefix, c.Capacity)
	if c.Location != nil {
		fmt.Fprintf(buf, "%s\tLocation: &%s%s,\n", linePrefix, typePrefix, c.Location.GnoLiteral(typePrefix, linePrefix+"\t"))
	}
	buf.WriteString(linePrefix)
	buf.WriteString("}")
	return buf.String()
}

func (c *CreateEventResponse) GnoLiteral(typePrefix string, linePrefix string) string {
	buf := &strings.Builder{}
	buf.WriteString(typePrefix)
	buf.WriteString("CreateEventResponse{\n")
	fmt.Fprintf(buf, "%s\tId: %q,\n", linePrefix, c.Id)
	buf.WriteString(linePrefix)
	buf.WriteString("}")
	return buf.String()
}

func (e *EditEventRequest) GnoLiteral(typePrefix string, linePrefix string) string {
	buf := &strings.Builder{}
	buf.WriteString(typePrefix)
	buf.WriteString("EditEventRequest{\n")
	fmt.Fprintf(buf, "%s\tEventId: %q,\n", linePrefix, e.EventId)
	fmt.Fprintf(buf, "%s\tTitle: %q,\n", linePrefix, e.Title)
	fmt.Fprintf(buf, "%s\tDescription: %q,\n", linePrefix, e.Description)
	fmt.Fprintf(buf, "%s\tImageUri: %q,\n", linePrefix, e.ImageUri)
	fmt.Fprintf(buf, "%s\tStartDate: %d,\n", linePrefix, e.StartDate)
	fmt.Fprintf(buf, "%s\tEndDate: %d,\n", linePrefix, e.EndDate)
	fmt.Fprintf(buf, "%s\tTicketPrice: %g,\n", linePrefix, e.TicketPrice)
	fmt.Fprintf(buf, "%s\tCapacity: %d,\n", linePrefix, e.Capacity)
	if e.Location != nil {
		fmt.Fprintf(buf, "%s\tLocation: &%s%s,\n", linePrefix, typePrefix, e.Location.GnoLiteral(typePrefix, linePrefix+"\t"))
	}
	buf.WriteString(linePrefix)
	buf.WriteString("}")
	return buf.String()
}

func (e *EditEventResponse) GnoLiteral(typePrefix string, linePrefix string) string {
	buf := &strings.Builder{}
	buf.WriteString(typePrefix)
	buf.WriteString("EditEventResponse{\n")
	fmt.Fprintf(buf, "%s\tId: %q,\n", linePrefix, e.Id)
	buf.WriteString(linePrefix)
	buf.WriteString("}")
	return buf.String()
}

func (p *ParticipateRequest) GnoLiteral(typePrefix string, linePrefix string) string {
	buf := &strings.Builder{}
	buf.WriteString(typePrefix)
	buf.WriteString("ParticipateRequest{\n")
	fmt.Fprintf(buf, "%s\tEventId: %q,\n", linePrefix, p.EventId)
	fmt.Fprintf(buf, "%s\tEmail: %q,\n", linePrefix, p.Email)
	buf.WriteString(linePrefix)
	buf.WriteString("}")
	return buf.String()
}

func (p *ParticipateResponse) GnoLiteral(typePrefix string, linePrefix string) string {
	buf := &strings.Builder{}
	buf.WriteString(typePrefix)
	buf.WriteString("ParticipateResponse{\n")
	fmt.Fprintf(buf, "%s\tTicketSecret: %q,\n", linePrefix, p.TicketSecret)
	buf.WriteString(linePrefix)
	buf.WriteString("}")
	return buf.String()
}

func (e *EventLocation) GnoLiteral(typePrefix string, linePrefix string) string {
	buf := &strings.Builder{}
	buf.WriteString(typePrefix)
	buf.WriteString("EventLocation{\n")
	fmt.Fprintf(buf, "%s\tVenueName: %q,\n", linePrefix, e.VenueName)
	fmt.Fprintf(buf, "%s\tInstructions: %q,\n", linePrefix, e.Instructions)
	switch val := e.Address.(type) {
	case *EventLocation_Geo:
		fmt.Fprintf(buf, "%s\tAddress: &%s,\n", linePrefix, val.Geo.GnoLiteral(typePrefix, linePrefix+"\t"))
	case *EventLocation_Virtual:
		fmt.Fprintf(buf, "%s\tAddress: &%s,\n", linePrefix, val.Virtual.GnoLiteral(typePrefix, linePrefix+"\t"))
	case *EventLocation_Custom:
		fmt.Fprintf(buf, "%s\tAddress: &%s,\n", linePrefix, val.Custom.GnoLiteral(typePrefix, linePrefix+"\t"))
	default:
		panic(errors.New("unknown address variant"))
	}
	buf.WriteString(linePrefix)
	buf.WriteString("}")
	return buf.String()
}

func (a *AddressVirtual) GnoLiteral(typePrefix string, linePrefix string) string {
	buf := &strings.Builder{}
	buf.WriteString(typePrefix)
	buf.WriteString("AddressVirtual{\n")
	fmt.Fprintf(buf, "%s\tUri: %q,\n", linePrefix, a.Uri)
	buf.WriteString(linePrefix)
	buf.WriteString("}")
	return buf.String()
}

func (a *AddressGeo) GnoLiteral(typePrefix string, linePrefix string) string {
	buf := &strings.Builder{}
	buf.WriteString(typePrefix)
	buf.WriteString("AddressGeo{\n")
	fmt.Fprintf(buf, "%s\tAddress: %q,\n", linePrefix, a.Address)
	fmt.Fprintf(buf, "%s\tLat: %g,\n", linePrefix, a.Lat)
	fmt.Fprintf(buf, "%s\tLng: %g,\n", linePrefix, a.Lng)
	fmt.Fprintf(buf, "%s\tSize: %g,\n", linePrefix, a.Size)
	buf.WriteString(linePrefix)
	buf.WriteString("}")
	return buf.String()
}

func (a *AddressCustom) GnoLiteral(typePrefix string, linePrefix string) string {
	buf := &strings.Builder{}
	buf.WriteString(typePrefix)
	buf.WriteString("AddressCustom{\n")
	fmt.Fprintf(buf, "%s\tAddress: %q,\n", linePrefix, a.Address)
	fmt.Fprintf(buf, "%s\tTimezone: %q,\n", linePrefix, a.Timezone)
	buf.WriteString(linePrefix)
	buf.WriteString("}")
	return buf.String()
}

func (e *EventInfo) GnoLiteral(typePrefix string, linePrefix string) string {
	buf := &strings.Builder{}
	buf.WriteString(typePrefix)
	buf.WriteString("EventInfo{\n")
	fmt.Fprintf(buf, "%s\tTitle: %q,\n", linePrefix, e.Title)
	fmt.Fprintf(buf, "%s\tDescription: %q,\n", linePrefix, e.Description)
	fmt.Fprintf(buf, "%s\tImageUri: %q,\n", linePrefix, e.ImageUri)
	fmt.Fprintf(buf, "%s\tCreator: %q,\n", linePrefix, e.Creator)
	fmt.Fprintf(buf, "%s\tStartDate: %d,\n", linePrefix, e.StartDate)
	fmt.Fprintf(buf, "%s\tEndDate: %d,\n", linePrefix, e.EndDate)
	fmt.Fprintf(buf, "%s\tCapacity: %d,\n", linePrefix, e.Capacity)
	if e.Location != nil {
		fmt.Fprintf(buf, "%s\tLocation: &%s%s,\n", linePrefix, typePrefix, e.Location.GnoLiteral(typePrefix, linePrefix+"\t"))
	}
	fmt.Fprintf(buf, "%s\tParticipants: %d,\n", linePrefix, e.Participants)
	fmt.Fprintf(buf, "%s\tPkgPath: %q,\n", linePrefix, e.PkgPath)
	buf.WriteString(linePrefix)
	buf.WriteString("}")
	return buf.String()
}

func (b *BatchProfileField) GnoLiteral(typePrefix string, linePrefix string) string {
	buf := &strings.Builder{}
	buf.WriteString(typePrefix)
	buf.WriteString("BatchProfileField{\n")
	fmt.Fprintf(buf, "%s\tType: %q,\n", linePrefix, b.Type)
	fmt.Fprintf(buf, "%s\tKey: %q,\n", linePrefix, b.Key)
	buf.WriteString(linePrefix)
	buf.WriteString("}")
	return buf.String()
}

