name: Buf Lint

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  buf-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Buf lint
        run: make lint-buf
