name: Buf Lint

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  buf-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-setup-action@v1.50.0
        with:
          version: 1.50.0
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Buf lint
        run: buf lint
