name: JS Build

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  check-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go.mod
          cache-key-suffix: js-build

      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version-file: ".nvmrc"

      - name: Install node modules
        run: npm ci

      - name: Build
        run: npm run build | go run ./cmd/next-route-checker
