name: JS

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  merge_group:

jobs:
  check-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version-file: ".nvmrc"

      - name: Install node modules
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npx prettier --check "**/*.{ts,tsx,js,jsx,json,css,md}" --ignore-path .gitignore --ignore-unknown

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_test_placeholder"
          NEXT_PUBLIC_ZENAO_BACKEND_ENDPOINT: "http://localhost:4242"
          NEXT_PUBLIC_ZENAO_NAMESPACE: "zenao"
          NEXT_PUBLIC_GATEWAY_URL: "placeholder.mypinata.cloud"
          NEXT_PUBLIC_STRIPE_DASHBOARD_URL: "https://dashboard.stripe.com/test"

      - name: Check that there is no diff
        run: git diff --exit-code
